from selenium import webdriver
import time
search_queries = search_queries = [
    "Best movies of all time",
    "How to start a small business",
    "Delicious pasta recipes",
    "Famous historical landmarks",
    # "Upcoming music festivals near me",
    # "Beginner's guide to coding",
    # "Health benefits of yoga",
    # "DIY home improvement ideas",
    # "Latest fashion trends",
    # "Top travel destinations in Europe",
    # "Mental health resources",
    # "Understanding climate change",
    # "How to invest in stocks",
    # "Famous quotes about success",
    # "Best hiking trails in the US",
    # "Easy dessert recipes",
    # "Learning a new language tips",
    # "Introduction to mindfulness meditation",
    # "Career paths in technology",
    # "Historical events that changed the world",
    # "Best mobile apps for productivity",
    # "Famous paintings and their artists",
    # "Home workout routines without equipment",
    # "DIY natural skincare remedies",
    # "Basics of cryptocurrency",
    # "Must-read books of all time",
    # "Travel photography tips",
    # "Healthy breakfast ideas",
    # "Self-care practices for stress relief",
    # "How to play guitar",
    # "Art museums in major cities",
    # "How does the internet work?",
    # "Tips for better sleep quality",
    # "Sustainable living practices",
    # "Understanding artificial intelligence",
    # "Classic novels everyone should read",
    # "Top TED Talks on various subjects",
    # "Delicious vegetarian dinner ideas",
    # "How to ace a job interview",
    # "Beginner's guide to photography",
    # "Virtual tour of famous landmarks",
    # "Famous speeches in history",
    # "Mind-bending riddles and puzzles",
    # "Basics of cooking for beginners",
    # "Best online courses for learning",
    # "Popular board games to play",
    # "Relationship advice for couples",
    # "Introduction to philosophy",
    # "Travel essentials packing list",
    # "How to build a personal budget",
    # "Learning to dance for beginners",
    # "Understanding quantum physics",
    # "Best podcasts for motivation",
    # "Famous historical battles",
    # "Outdoor camping essentials",
    # "Nutrition tips for a healthy lifestyle",
    # "DIY fashion and clothing ideas",
    # "How to create a blog",
    # "Introduction to astronomy",
    # "Effective communication skills",
    # "Popular video games and reviews",
    # "Easy woodworking projects for beginners",
    # "Meditation techniques for stress relief",
    # "Financial planning for retirement",
    # "Tips for successful gardening",
    # "Creative writing prompts",
    # "Famous architects and their works",
    # "How to bake bread at home",
    # "Basics of graphic design",
    # "Volunteering opportunities in my area",
    # "Understanding different musical genres",
    # "Tips for time management",
    # "Best documentaries of all time",
    # "Basic car maintenance tips",
    # "Introduction to world religions",
    # "Healthy snack ideas for kids",
    # "How to start investing in real estate",
    # "Learn to code for free online",
    # "Mindfulness exercises for beginners",
    # "Popular cocktail recipes",
    # "Tips for public speaking confidence",
    # "Understanding global economics",
    # "Easy DIY home organization hacks",
    # "Must-visit beaches around the world",
    # "Basics of renewable energy sources",
    # "How to care for indoor plants",
    # "Essential kitchen tools for cooking",
    # "Introduction to classical music composers",
    # "Personal finance management strategies",
    # "Beginner's guide to interior design",
    # "Famous sculptures and their artists",
    # "Basics of cybersecurity",
    # "Effective workout routines for weight loss",
    # "How to plan a budget-friendly vacation",
    # "Learning to draw step-by-step",
    # "Best strategies for job hunting",
    # "Introduction to world geography",
    # "Tips for effective studying",
    # "Famous fashion designers and their influence",
    # "How to stay motivated and productive"
]
edge_options = webdriver.EdgeOptions()
driver = webdriver.Edge(options=edge_options)
for query in search_queries:
    driver.get("https://www.bing.com")
    search_box = driver.find_element("name", "q")
    search_box.send_keys(query)
    search_box.submit()
    time.sleep(7)
driver.quit()
